### ISSUE TITLE
Support for setting random seed.

### ISSUE THREAD

**Issue by vangorra** [primaryobjects/lda#10]
It would be super helpful if we could set a seed for the randomizer. This feature would give us predictable tests and better flexibility.

While there are other libraries that could be used, there are many simple function implementations that would serve the purpose.

For example:
http://stackoverflow.com/a/19303725/1267536

I can make the PR if you're willing to accept the feature.

**Comment by primaryobjects** [comment]
Right, this would allow the same results to be obtained upon subsequent runs. The only issue is how to get an accurate random number generator with a seed. It looks like in the sample link you provided, if you give a large enough value to the multiplier, the random numbers [appear](http://jsfiddle.net/bhrLT/86/) more uniform.

There are 2 locations in the code that use a random number, on line [148](https://github.com/primaryobjects/lda/blob/master/lib/lda.js#L148) and [214](https://github.com/primaryobjects/lda/blob/master/lib/lda.js#L214).
