### ISSUE TITLE
Feature -  API could allow the corpus to be created accretively

### ISSUE THREAD

**Issue by 0o-de-lally** [primaryobjects/lda#12]
I'd like to be able to add sentences over time to the corpus, and not all at once.
Something like:
`
var index = lda.addSentence('string')
// returns an array index or unique id
`

which later could use:

`
var topicModel = lda.process(index, numTopics, termsPer)
`

@primaryobjects do you have any thoughts on this?

**Comment by primaryobjects** [comment]
lda works by building a dictionary of all unique terms, so it needs to know all of the words ahead of time. What you could do though, is when adding a new word, rebuild the dictionary and recalculate the topics.

Feel free to fork! :)

**Comment by mikelax** [comment]
Similar to what @lpgeiger suggested above would be to separate the logic of executing the calculation from that of constructing the lda object and building the document list. 

So you could add new functions such as:  
`addDocument(doc)`
`addDocuments(docsArray)`
`execute(numTopics, termCount)`
