### ISSUE TITLE
Error in function with empty string in middle of Array

### ISSUE THREAD

**Issue by mikelax** [primaryobjects/lda#13]
There is a bug in how the lda function is reading the Array values. If there is an empty string in the middle of the Array then an `undefined` error is thrown. 

Example:
```js
const lda = require('lda');

const s1 = ['Lots of people have dogs as pets',
  'Another sentence about cats and dogs together, they get along',
  '',
  'One more sentence about dogs',

const results = lda(s1, 3, 2);
];
```

Result:
```
/test/node_modules/lda/lib/lda.js:149
            var N = this.documents[m].length;
                                     ^

TypeError: Cannot read property 'length' of undefined
    at initialState (/test/node_modules/lda/lib/lda.js:149:38)
```

If you remove the empty string from the `s1` array, or move it to be the last element in the Array then things work as expected.

**Comment by primaryobjects** [comment]
Resolved in lda 0.2.0 https://github.com/primaryobjects/lda/commit/fb7a83d46ef9c43658bce7921f1411ddde65e3ad

Thank you! :)
