### ISSUE TITLE
Same word appearing in different topics?

### ISSUE THREAD

**Issue by deemeetree** [primaryobjects/lda#15]
Hello, thank you for this great tool.

Is it normal that the same word appears in different topics? For example, 

Topic 1: _topic_   text   data  
Topic 2: modeling   _topic_   introduction

**Comment by primaryobjects** [comment]
Yes, see [here](https://stackoverflow.com/a/19551968). Thanks!

_"LDA topics are probability distributions over terms. Terms may have nonzero weight in any or all of the topics. You can turn that around and find the probability of each topic given a specific term. So yes, a term like "bank" can be assigned to many topics, but in general it will be assigned to some with a stronger weight than others."_
